package it.nexera.ris.common.enums;

public enum ApplicationSettingsKeys {
    // Common settings
    PASSWORD_EXPIRATION_PERIOD,
    PERMISSION_IMPORT_FORMALITY,
    PERMISSION_IMPORT_REPORT_FORMALITY_SUBJECT,

    FILE_ENTITY_PATH,

    TYPE_FORMALITY_ADDITIONAL_DATA_IMPORTED,

    RECEIVED_SERVER_ID(true),
    SENT_SERVER_ID(true),

    DOCUMENT_PATH_FORMALITY,
    DOCUMENT_PATH_CADASTRAL,
    DOCUMENT_PATH_ESTATE_FORMALITY,
    DOCUMENT_PATH_OTHER,

    SESSION_TIMEOUT,
    SESSION_CHECK_TIMEOUT,

    IMPORT_PROPERTY_PATH,
    IMPORT_PROPERTY_INTERVAL,
    IMPORT_ESTATE_FORMALITY_PATH,
    IMPORT_ESTATE_FORMALITY_INTERVAL,
    IMPORT_FORMALITY_PATH,
    IMPORT_FORMALITY_INTERVAL,
    IMPORT_FORMALITY_NUMBER_FILES,
    IMPORT_REPORT_FORMALITY_SUBJECT_PATH,
    IMPORT_REPORT_FORMALITY_SUBJECT_INTERVAL,
    IMPORT_REPORT_FORMALITY_SUBJECT_NUMBER_FILES,
    IMPORT_SUB,
    IMPORT_VISURE_RTF_PATH,
    IMPORT_VISURE_RTF_INTERVAL,
    IMPORT_VISURE_RTF_NUMBER_FILES,
    IMPORT_VISURE_RTF_PATH_FILES_SERVER,
    IMPORT_VISURE_DH_PATH,
    IMPORT_VISURE_DH_INTERVAL,
    IMPORT_VISURE_DH_NUMBER_FILES,
    IMPORT_REQUEST_OLD_PATH,
    IMPORT_REQUEST_OLD_INTERVAL,
    IMPORT_REQUEST_OLD_NUMBER_FILES,

    SOFFICE_COMMAND,
    SOFFICE_TEMP_DIR_PREFIX,

    DOCUMENT_CONVERSION_HEADER_IMAGE,
    DOCUMENT_CONVERSION_FOOTER_IMAGE,

    OMI_KML_FILES,
    OMI_SECURITIES_FILE,
    OMI_CATEGORY_FILE,
    
    COMPANY_NAME,
    FISCAL_CODE,
    ADDRESS,
    COMPANY_POSTAL_CODE,
    COMPANY_PROVINCE,
    COMPANY_CITY,
    
    CLIENT_CONSERVATIVE_CODE_FILES,
    TABLE_CONSERVATIVE_CODE_FILES,
    DTD,

    CLOUD_API_URL,
    CLOUD_API_KEY
    ;

    boolean needToRefresh;

    ApplicationSettingsKeys() {
    }

    ApplicationSettingsKeys(boolean needToRefresh) {
        this.needToRefresh = needToRefresh;
    }

    public boolean isNeedToRefresh() {
        return needToRefresh;
    }
}
