package it.nexera.ris.common.enums;

public enum RequestTextEditCommentType {

    SELECTED_PROPERTY,
    SELECTED_ESTATE_FORMALITY,
    SELECTED_FORMALITY,
    SELECTED_ESTATE_SITUATION,
    SELECTED_ESTATE_SITUATION_INIT,
    NOT_SELECTED_PROPERTY,
    NOT_SELECTED_ESTATE_FORMALITY,
    FORMALITY_DISTRAINT_COMMENT,
    REQUEST,
    COMMENT_CERTIFICATION,
    FORMALITY_COMMENT_CERTIFICATION;

    RequestTextEditCommentType() {
    }


}
